# Nome da Aplicacao
spring.application.name=game-store

# Configuracoes de Conexao com o Banco de Dados (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/db-game_store
spring.datasource.username=${DB_GAME_STORE_USERNAME}
spring.datasource.password=${DB_GAME_STORE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracoes do JPA/Hibernate
# Mostra os comandos SQL no console (otimo para debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Como voce vai usar Migrations (Flyway) depois,
# deixamos o Hibernate apenas atualizar a base por enquanto.
spring.jpa.hibernate.ddl-auto=validate